# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import initdaemon_pb2 as initdaemon__pb2


class InitDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPhauls = channel.unary_unary(
                '/initdaemon.InitDaemon/RunPhauls',
                request_serializer=initdaemon__pb2.ServerInfo.SerializeToString,
                response_deserializer=initdaemon__pb2.Result.FromString,
                )
        self.RunPhaulc = channel.unary_unary(
                '/initdaemon.InitDaemon/RunPhaulc',
                request_serializer=initdaemon__pb2.ClientInfo.SerializeToString,
                response_deserializer=initdaemon__pb2.Result.FromString,
                )


class InitDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunPhauls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPhaulc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InitDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPhauls': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPhauls,
                    request_deserializer=initdaemon__pb2.ServerInfo.FromString,
                    response_serializer=initdaemon__pb2.Result.SerializeToString,
            ),
            'RunPhaulc': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPhaulc,
                    request_deserializer=initdaemon__pb2.ClientInfo.FromString,
                    response_serializer=initdaemon__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'initdaemon.InitDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InitDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPhauls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/initdaemon.InitDaemon/RunPhauls',
            initdaemon__pb2.ServerInfo.SerializeToString,
            initdaemon__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunPhaulc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/initdaemon.InitDaemon/RunPhaulc',
            initdaemon__pb2.ClientInfo.SerializeToString,
            initdaemon__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
