version: '2'
services:
    frontend:
        image: taisyou
        container_name: frontend
        init: true
        command: "/root/main ruby /root/zipkin-ruby-example/frontend.rb -o 0.0.0.0"
        networks:
            - test_network
        ports:
            - 8081:8081
        dns: 192.168.16.3
        privileged: true
        tmpfs:
            - /run
        volumes:
            - ./image:/root/image
        depends_on:
            - "backend"
            - "coredns"
            - "zipkin"
        environment:
            - SERVICE_NAME=frontend


    backend:
        image: taisyou 
        container_name: backend
        init: true
        command: "/root/main ruby /root/zipkin-ruby-example/backend.rb -o 0.0.0.0"
#        command: "ruby /root/zipkin-ruby-example/backend.rb -o 0.0.0.0"
        networks:
            - test_network
        ports: 
            - 8083:8081
            - 9000:9000
        dns: 192.168.16.3
        privileged: true
        tmpfs:
            - /run
        volumes:
            - ./image:/root/image
        depends_on:
            - "coredns"
            - "zipkin"
        extra_hosts:
            - "backend:192.168.16.5"
        environment:
            - SERVICE_NAME=backend

    coredns:
        image: coredns/coredns:1.3.1
        container_name: coredns
        volumes:
            - ./coredns:/root/coredns
        networks:
            test_network:
                ipv4_address: 192.168.16.3
        ports:
            - 53:53/udp
        command: -conf "/root/coredns/Corefile"
        environment:
            - ETCD_IP=192.168.16.2
            
    etcd:
        image: quay.io/coreos/etcd:v3.3.11
        container_name: etcd
        networks:
            test_network:
                ipv4_address: 192.168.16.2
        ports:
            - 2379:2379
            - 2380:2380
            - 4001:4001
        command: >
            etcd  
            -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
            -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001

    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        networks:
            - test_network
        ports: 
            - 9411:9411
        depends_on:
            - "coredns"

networks:
    test_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.16.0/24
