# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: initdaemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='initdaemon.proto',
  package='initdaemon',
  syntax='proto3',
  serialized_options=b'Z&github.com/takaie0214/initdaemon/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10initdaemon.proto\x12\ninitdaemon\"1\n\nServerInfo\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x13\n\x0bservicename\x18\x02 \x01(\t\"?\n\nClientInfo\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x13\n\x0bservicename\x18\x02 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\x82\x01\n\nInitDaemon\x12\x39\n\tRunPhauls\x12\x16.initdaemon.ServerInfo\x1a\x12.initdaemon.Result\"\x00\x12\x39\n\tRunPhaulc\x12\x16.initdaemon.ClientInfo\x1a\x12.initdaemon.Result\"\x00\x42(Z&github.com/takaie0214/initdaemon/protob\x06proto3'
)




_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='initdaemon.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='initdaemon.ServerInfo.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='servicename', full_name='initdaemon.ServerInfo.servicename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=81,
)


_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='initdaemon.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='initdaemon.ClientInfo.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='servicename', full_name='initdaemon.ClientInfo.servicename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addr', full_name='initdaemon.ClientInfo.addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=146,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='initdaemon.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='initdaemon.Result.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'initdaemon_pb2'
  # @@protoc_insertion_point(class_scope:initdaemon.ServerInfo)
  })
_sym_db.RegisterMessage(ServerInfo)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'initdaemon_pb2'
  # @@protoc_insertion_point(class_scope:initdaemon.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'initdaemon_pb2'
  # @@protoc_insertion_point(class_scope:initdaemon.Result)
  })
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None

_INITDAEMON = _descriptor.ServiceDescriptor(
  name='InitDaemon',
  full_name='initdaemon.InitDaemon',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=172,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunPhauls',
    full_name='initdaemon.InitDaemon.RunPhauls',
    index=0,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunPhaulc',
    full_name='initdaemon.InitDaemon.RunPhaulc',
    index=1,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INITDAEMON)

DESCRIPTOR.services_by_name['InitDaemon'] = _INITDAEMON

# @@protoc_insertion_point(module_scope)
